version: '3'

tasks:
  install:
    desc: Установка зависимостей проекта
    cmds:
      - pip install -r requirements.txt
      - pip install pyinstaller

  run:
    desc: Запуск приложения
    cmds:
      - python main.py

  build:
    desc: Сборка для текущей платформы с уменьшением размера бинарника
    deps: [install]
    cmds:
      - python convert_icon.py
      - pyinstaller --onefile --strip --noconsole --name translator --icon ui/icons/icon.ico --add-data "settings.json:." --add-data "ui/icons/*:ui/icons" main.py

  build-windows:
    desc: Сборка для Windows с минимальным размером (убедитесь, что UPX установлен)
    deps: [install]
    cmds:
      - python convert_icon.py
      - pyinstaller --onefile --noconsole --name translator.exe --icon ui/icons/icon.ico --add-data "settings.json;." --add-data "ui/icons/*;ui/icons" --distpath ./dist/windows main.py

  build-linux:
    desc: Кросс-компиляция для Linux через Docker с уменьшенным размером (в контейнере можно применять --strip)
    cmds:
      - docker build -t translator-linux .
      - docker create --name temp translator-linux
      - docker cp temp:translator ./dist/linux/
      - docker rm temp
      - docker rmi translator-linux

  build-mac:
    desc: Сборка для MacOS с уменьшением размера бинарника
    deps: [install]
    cmds:
      - python convert_icon.py
      - pyinstaller --onefile --strip --noconsole --name translator --icon ui/icons/icon.png --add-data "settings.json:." --add-data "ui/icons/*:ui/icons" --distpath ./dist/macos main.py

  clean:
    desc: Очистка артефактов сборки
    cmds:
      - rm -rf build dist *.spec

  test:
    desc: Запуск тестов (если есть)
    cmds:
      - python -m pytest tests/

  ruff-check:
    desc: Проверка стиля кода с помощью ruff
    deps: [install]
    cmds:
      - python -m ruff check .

  ruff-format-check:
    desc: Проверка форматирования кода
    deps: [install]
    cmds:
      - python -m ruff format --check .

  ruff:
    desc: Полная проверка кода с помощью ruff
    deps: [ruff-check, ruff-format-check]

  format:
    desc: Автоматическое форматирование кода
    deps: [install]
    cmds:
      - python -m ruff format .

  fix:
    desc: Автоматическое исправление проблем с кодом
    deps: [install]
    cmds:
      - python -m ruff check --fix .

  lint:
    desc: Полная проверка кода
    deps: [ruff]
    cmds:
      - python -m mypy .